/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
// TODO: Implement custom contract types
// import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
type GenericContractsDeclaration = any;

const deployedContracts = {
  23295: {
    SimpleBet: {
      address: "0x36A7f9ca3EBD83E00c1bca3A1db378bcF039Bf85",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "domain",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "A13e_RevokedAuthToken",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_AddressMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_ChainIdMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_DomainMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_Expired",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_NotBeforeInFuture",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweParser_InvalidAddressLength",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweParser_InvalidNonce",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "subBetCount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "BetPlaced",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum SimpleBet.BetStatus",
              name: "status",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
          ],
          name: "BetResolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "FundsWithdrawn",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "platform",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "marketId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "enum SimpleBet.BetOutcome",
              name: "outcome",
              type: "uint8",
            },
          ],
          name: "SubBetPlaced",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
          ],
          name: "cancelBet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "domain",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "getAllBets",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "enum SimpleBet.BetOutcome",
                  name: "outcome",
                  type: "uint8",
                },
                {
                  internalType: "enum SimpleBet.BetStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "string",
                      name: "platform",
                      type: "string",
                    },
                    {
                      internalType: "uint256",
                      name: "amount",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "marketId",
                      type: "string",
                    },
                    {
                      internalType: "enum SimpleBet.BetOutcome",
                      name: "outcome",
                      type: "uint8",
                    },
                    {
                      internalType: "enum SimpleBet.BetStatus",
                      name: "status",
                      type: "uint8",
                    },
                    {
                      internalType: "uint256",
                      name: "payout",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct SimpleBet.SubBet[]",
                  name: "subBets",
                  type: "tuple[]",
                },
                {
                  internalType: "uint256",
                  name: "totalPayout",
                  type: "uint256",
                },
              ],
              internalType: "struct SimpleBet.Bet[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "betIndex",
              type: "uint256",
            },
          ],
          name: "getBet",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "enum SimpleBet.BetOutcome",
                  name: "outcome",
                  type: "uint8",
                },
                {
                  internalType: "enum SimpleBet.BetStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "string",
                      name: "platform",
                      type: "string",
                    },
                    {
                      internalType: "uint256",
                      name: "amount",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "marketId",
                      type: "string",
                    },
                    {
                      internalType: "enum SimpleBet.BetOutcome",
                      name: "outcome",
                      type: "uint8",
                    },
                    {
                      internalType: "enum SimpleBet.BetStatus",
                      name: "status",
                      type: "uint8",
                    },
                    {
                      internalType: "uint256",
                      name: "payout",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct SimpleBet.SubBet[]",
                  name: "subBets",
                  type: "tuple[]",
                },
                {
                  internalType: "uint256",
                  name: "totalPayout",
                  type: "uint256",
                },
              ],
              internalType: "struct SimpleBet.Bet",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
          ],
          name: "getBetSummary",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "enum SimpleBet.BetStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "subBetCount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPayout",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getContractBalance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getOwner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
          ],
          name: "getSubBets",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "platform",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "marketId",
                  type: "string",
                },
                {
                  internalType: "enum SimpleBet.BetOutcome",
                  name: "outcome",
                  type: "uint8",
                },
                {
                  internalType: "enum SimpleBet.BetStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "payout",
                  type: "uint256",
                },
              ],
              internalType: "struct SimpleBet.SubBet[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalBets",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserBetCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "getUserBets",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "enum SimpleBet.BetOutcome",
                  name: "outcome",
                  type: "uint8",
                },
                {
                  internalType: "enum SimpleBet.BetStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "string",
                      name: "platform",
                      type: "string",
                    },
                    {
                      internalType: "uint256",
                      name: "amount",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "marketId",
                      type: "string",
                    },
                    {
                      internalType: "enum SimpleBet.BetOutcome",
                      name: "outcome",
                      type: "uint8",
                    },
                    {
                      internalType: "enum SimpleBet.BetStatus",
                      name: "status",
                      type: "uint8",
                    },
                    {
                      internalType: "uint256",
                      name: "payout",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct SimpleBet.SubBet[]",
                  name: "subBets",
                  type: "tuple[]",
                },
                {
                  internalType: "uint256",
                  name: "totalPayout",
                  type: "uint256",
                },
              ],
              internalType: "struct SimpleBet.Bet[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "siweMsg",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "r",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "s",
                  type: "bytes32",
                },
                {
                  internalType: "uint256",
                  name: "v",
                  type: "uint256",
                },
              ],
              internalType: "struct SignatureRSV",
              name: "sig",
              type: "tuple",
            },
          ],
          name: "login",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
          ],
          name: "ownerWithdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "enum SimpleBet.BetOutcome",
              name: "outcome",
              type: "uint8",
            },
            {
              internalType: "string[]",
              name: "platforms",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "marketIds",
              type: "string[]",
            },
          ],
          name: "placeBet",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "won",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
          ],
          name: "resolveBet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
          ],
          name: "transferContractBalance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userBalances",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawBalance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        domain: "@oasisprotocol/sapphire-contracts/contracts/auth/SiweAuth.sol",
        login: "@oasisprotocol/sapphire-contracts/contracts/auth/SiweAuth.sol",
      },
      deployedOnBlock: 13720277,
    },
  },
  31337: {
    SimpleBet: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "domain",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "A13e_RevokedAuthToken",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_AddressMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_ChainIdMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_DomainMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_Expired",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweAuth_NotBeforeInFuture",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweParser_InvalidAddressLength",
          type: "error",
        },
        {
          inputs: [],
          name: "SiweParser_InvalidNonce",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "subBetCount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "BetPlaced",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum SimpleBet.BetStatus",
              name: "status",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
          ],
          name: "BetResolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "FundsWithdrawn",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "platform",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "marketId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "enum SimpleBet.BetOutcome",
              name: "outcome",
              type: "uint8",
            },
          ],
          name: "SubBetPlaced",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
          ],
          name: "cancelBet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "domain",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "getAllBets",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "enum SimpleBet.BetOutcome",
                  name: "outcome",
                  type: "uint8",
                },
                {
                  internalType: "enum SimpleBet.BetStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "string",
                      name: "platform",
                      type: "string",
                    },
                    {
                      internalType: "uint256",
                      name: "amount",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "marketId",
                      type: "string",
                    },
                    {
                      internalType: "enum SimpleBet.BetOutcome",
                      name: "outcome",
                      type: "uint8",
                    },
                    {
                      internalType: "enum SimpleBet.BetStatus",
                      name: "status",
                      type: "uint8",
                    },
                    {
                      internalType: "uint256",
                      name: "payout",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct SimpleBet.SubBet[]",
                  name: "subBets",
                  type: "tuple[]",
                },
                {
                  internalType: "uint256",
                  name: "totalPayout",
                  type: "uint256",
                },
              ],
              internalType: "struct SimpleBet.Bet[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "betIndex",
              type: "uint256",
            },
          ],
          name: "getBet",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "enum SimpleBet.BetOutcome",
                  name: "outcome",
                  type: "uint8",
                },
                {
                  internalType: "enum SimpleBet.BetStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "string",
                      name: "platform",
                      type: "string",
                    },
                    {
                      internalType: "uint256",
                      name: "amount",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "marketId",
                      type: "string",
                    },
                    {
                      internalType: "enum SimpleBet.BetOutcome",
                      name: "outcome",
                      type: "uint8",
                    },
                    {
                      internalType: "enum SimpleBet.BetStatus",
                      name: "status",
                      type: "uint8",
                    },
                    {
                      internalType: "uint256",
                      name: "payout",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct SimpleBet.SubBet[]",
                  name: "subBets",
                  type: "tuple[]",
                },
                {
                  internalType: "uint256",
                  name: "totalPayout",
                  type: "uint256",
                },
              ],
              internalType: "struct SimpleBet.Bet",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
          ],
          name: "getBetSummary",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "enum SimpleBet.BetStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "subBetCount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPayout",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getContractBalance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getOwner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
          ],
          name: "getSubBets",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "platform",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "marketId",
                  type: "string",
                },
                {
                  internalType: "enum SimpleBet.BetOutcome",
                  name: "outcome",
                  type: "uint8",
                },
                {
                  internalType: "enum SimpleBet.BetStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "payout",
                  type: "uint256",
                },
              ],
              internalType: "struct SimpleBet.SubBet[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalBets",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserBetCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "getUserBets",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "enum SimpleBet.BetOutcome",
                  name: "outcome",
                  type: "uint8",
                },
                {
                  internalType: "enum SimpleBet.BetStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "string",
                      name: "platform",
                      type: "string",
                    },
                    {
                      internalType: "uint256",
                      name: "amount",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "marketId",
                      type: "string",
                    },
                    {
                      internalType: "enum SimpleBet.BetOutcome",
                      name: "outcome",
                      type: "uint8",
                    },
                    {
                      internalType: "enum SimpleBet.BetStatus",
                      name: "status",
                      type: "uint8",
                    },
                    {
                      internalType: "uint256",
                      name: "payout",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct SimpleBet.SubBet[]",
                  name: "subBets",
                  type: "tuple[]",
                },
                {
                  internalType: "uint256",
                  name: "totalPayout",
                  type: "uint256",
                },
              ],
              internalType: "struct SimpleBet.Bet[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "siweMsg",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "r",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "s",
                  type: "bytes32",
                },
                {
                  internalType: "uint256",
                  name: "v",
                  type: "uint256",
                },
              ],
              internalType: "struct SignatureRSV",
              name: "sig",
              type: "tuple",
            },
          ],
          name: "login",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
          ],
          name: "ownerWithdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "enum SimpleBet.BetOutcome",
              name: "outcome",
              type: "uint8",
            },
            {
              internalType: "string[]",
              name: "platforms",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "marketIds",
              type: "string[]",
            },
          ],
          name: "placeBet",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "betId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "won",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
          ],
          name: "resolveBet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "token",
              type: "bytes",
            },
          ],
          name: "transferContractBalance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userBalances",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawBalance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        domain: "@oasisprotocol/sapphire-contracts/contracts/auth/SiweAuth.sol",
        login: "@oasisprotocol/sapphire-contracts/contracts/auth/SiweAuth.sol",
      },
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
